from app import db
from models import *


db.drop_all()
db.create_all()


db.session.add_all([
  # armor types
  ArmorCategory(name='No Armor'), 
  ArmorCategory(name='Light Armor'), 
  ArmorCategory(name='Medium Armor'),
  ArmorCategory(name="Heavy Armor"), 
  ArmorCategory(name='Spell'),
  ArmorCategory(name='Class Feature'), 
  ArmorCategory(name='Shield'),  
  
  # API spells
  APISpell.create_api_spell("abhorrent-apparition", "Abhorrent Apparition"),
  APISpell.create_api_spell("accelerate", "Accelerate"),
  APISpell.create_api_spell("acid-arrow", "Acid Arrow"),
  APISpell.create_api_spell("acid-gate", "Acid Gate"),
  APISpell.create_api_spell("acid-rain", "Acid Rain"),
  APISpell.create_api_spell("acid-splash", "Acid Splash"),
  APISpell.create_api_spell("adjust-position", "Adjust Position"),
  APISpell.create_api_spell("afflict-line", "Afflict Line"),
  APISpell.create_api_spell("agonizing-mark", "Agonizing Mark"),
  APISpell.create_api_spell("aid", "Aid"),
  APISpell.create_api_spell("alarm", "Alarm"),
  APISpell.create_api_spell("alchemical-form", "Alchemical Form"),
  APISpell.create_api_spell("ale-dritch-blast", "Ale-dritch Blast"),
  APISpell.create_api_spell("ally-aegis", "Ally Aegis"),
  APISpell.create_api_spell("alone", "Alone"),
  APISpell.create_api_spell("alter-arrows-fortune", "Alter Arrow’s Fortune"),
  APISpell.create_api_spell("alter-self", "Alter Self"),
  APISpell.create_api_spell("altheas-travel-tent", "Althea’s Travel Tent"),
  APISpell.create_api_spell("amplify-gravity", "Amplify Gravity"),
  APISpell.create_api_spell("analyze-device", "Analyze Device"),
  APISpell.create_api_spell("ancestors-strength", "Ancestor’s Strength"),
  APISpell.create_api_spell("anchoring-rope", "Anchoring Rope"),
  APISpell.create_api_spell("ancient-shade", "Ancient Shade"),
  APISpell.create_api_spell("angelic-guardian", "Angelic Guardian"),
  APISpell.create_api_spell("animal-friendship", "Animal Friendship"),
  APISpell.create_api_spell("animal-messenger", "Animal Messenger"),
  APISpell.create_api_spell("animal-shapes", "Animal Shapes"),
  APISpell.create_api_spell("animate-dead", "Animate Dead"),
  APISpell.create_api_spell("animate-ghoul", "Animate Ghoul"),
  APISpell.create_api_spell("animate-greater-undead", "Animate Greater Undead"),
  APISpell.create_api_spell("animate-objects", "Animate Objects"),
  APISpell.create_api_spell("animated-scroll", "Animated Scroll"),
  APISpell.create_api_spell("anticipate-arcana", "Anticipate Arcana"),
  APISpell.create_api_spell("anticipate-attack", "Anticipate Attack"),
  APISpell.create_api_spell("anticipate-weakness", "Anticipate Weakness"),
  APISpell.create_api_spell("antilife-shell", "Antilife Shell"),
  APISpell.create_api_spell("antimagic-field", "Antimagic Field"),
  APISpell.create_api_spell("antipathysympathy", "Antipathy/Sympathy"),
  APISpell.create_api_spell("arcane-eye", "Arcane Eye"),
  APISpell.create_api_spell("arcane-hand", "Arcane Hand"),
  APISpell.create_api_spell("arcane-lock", "Arcane Lock"),
  APISpell.create_api_spell("arcane-sight", "Arcane Sight"),
  APISpell.create_api_spell("arcane-sword", "Arcane Sword"),
  APISpell.create_api_spell("arcanists-magic-aura", "Arcanist's Magic Aura"),
  APISpell.create_api_spell("as-you-were", "As You Were"),
  APISpell.create_api_spell("ashen-memories", "Ashen Memories"),
  APISpell.create_api_spell("aspect-of-the-dragon", "Aspect of the Dragon"),
  APISpell.create_api_spell("aspect-of-the-serpent", "Aspect of the Serpent"),
  APISpell.create_api_spell("astral-projection", "Astral Projection"),
  APISpell.create_api_spell("augury", "Augury"),
  APISpell.create_api_spell("aura-of-protection-or-destruction", "Aura of Protection or Destruction"),
  APISpell.create_api_spell("auspicious-warning", "Auspicious Warning"),
  APISpell.create_api_spell("avoid-grievous-injury", "Avoid Grievous Injury"),
  APISpell.create_api_spell("avronins-astral-assembly", "Avronin’s Astral Assembly"),
  APISpell.create_api_spell("awaken", "Awaken"),
  APISpell.create_api_spell("awaken-object", "Awaken Object"),
  APISpell.create_api_spell("bad-timing", "Bad Timing"),
  APISpell.create_api_spell("bane", "Bane"),
  APISpell.create_api_spell("banishment", "Banishment"),
  APISpell.create_api_spell("barkskin", "Barkskin"),
  APISpell.create_api_spell("batsense", "Batsense"),
  APISpell.create_api_spell("beacon-of-hope", "Beacon of Hope"),
  APISpell.create_api_spell("become-nightwing", "Become Nightwing"),
  APISpell.create_api_spell("beguiling-bet", "Beguiling Bet"),
  APISpell.create_api_spell("benediction", "Benediction"),
  APISpell.create_api_spell("bestial-fury", "Bestial Fury"),
  APISpell.create_api_spell("bestow-curse", "Bestow Curse"),
  APISpell.create_api_spell("binding-oath", "Binding Oath"),
  APISpell.create_api_spell("biting-arrow", "Biting Arrow"),
  APISpell.create_api_spell("bitter-chains", "Bitter Chains"),
  APISpell.create_api_spell("black-goats-blessing", "Black Goat’s Blessing"),
  APISpell.create_api_spell("black-hand", "Black Hand"),
  APISpell.create_api_spell("black-ribbons", "Black Ribbons"),
  APISpell.create_api_spell("black-sunshine", "Black Sunshine"),
  APISpell.create_api_spell("black-swan-storm", "Black Swan Storm"),
  APISpell.create_api_spell("black-tentacles", "Black Tentacles"),
  APISpell.create_api_spell("black-well", "Black Well"),
  APISpell.create_api_spell("blade-barrier", "Blade Barrier"),
  APISpell.create_api_spell("blade-of-wrath", "Blade of Wrath"),
  APISpell.create_api_spell("blade-of-my-brother", "Blade of my Brother"),
  APISpell.create_api_spell("blazing-chariot", "Blazing Chariot"),
  APISpell.create_api_spell("bleating-call", "Bleating Call"),
  APISpell.create_api_spell("bleed", "Bleed"),
  APISpell.create_api_spell("bless", "Bless"),
  APISpell.create_api_spell("bless-the-dead", "Bless the Dead"),
  APISpell.create_api_spell("blessed-halo", "Blessed Halo"),
  APISpell.create_api_spell("blight", "Blight"),
  APISpell.create_api_spell("blindnessdeafness", "Blindness/Deafness"),
  APISpell.create_api_spell("blink", "Blink"),
  APISpell.create_api_spell("blizzard", "Blizzard"),
  APISpell.create_api_spell("blood-armor", "Blood Armor"),
  APISpell.create_api_spell("blood-lure", "Blood Lure"),
  APISpell.create_api_spell("blood-offering", "Blood Offering"),
  APISpell.create_api_spell("blood-puppet", "Blood Puppet"),
  APISpell.create_api_spell("blood-scarab", "Blood Scarab"),
  APISpell.create_api_spell("blood-spoor", "Blood Spoor"),
  APISpell.create_api_spell("blood-tide", "Blood Tide"),
  APISpell.create_api_spell("blood-and-steel", "Blood and Steel"),
  APISpell.create_api_spell("blood-to-acid", "Blood to Acid"),
  APISpell.create_api_spell("bloodhound", "Bloodhound"),
  APISpell.create_api_spell("bloodshot", "Bloodshot"),
  APISpell.create_api_spell("bloody-hands", "Bloody Hands"),
  APISpell.create_api_spell("bloody-smite", "Bloody Smite"),
  APISpell.create_api_spell("bloom", "Bloom"),
  APISpell.create_api_spell("blur", "Blur"),
  APISpell.create_api_spell("boiling-blood", "Boiling Blood"),
  APISpell.create_api_spell("boiling-oil", "Boiling Oil"),
  APISpell.create_api_spell("bolster-undead", "Bolster Undead"),
  APISpell.create_api_spell("booster-shot", "Booster Shot"),
  APISpell.create_api_spell("boreass-breath", "Boreas’s Breath"),
  APISpell.create_api_spell("bottled-arcana", "Bottled Arcana"),
  APISpell.create_api_spell("bottomless-stomach", "Bottomless Stomach"),
  APISpell.create_api_spell("branding-smite", "Branding Smite"),
  APISpell.create_api_spell("breathtaking-wind", "Breathtaking Wind"),
  APISpell.create_api_spell("breeze-compass", "Breeze Compass"),
  APISpell.create_api_spell("brimstone-infusion", "Brimstone Infusion"),
  APISpell.create_api_spell("brittling", "Brittling"),
  APISpell.create_api_spell("broken-charge", "Broken Charge"),
  APISpell.create_api_spell("burning-hands", "Burning Hands"),
  APISpell.create_api_spell("by-the-light-of-the-moon", "By the Light of the Moon"),
  APISpell.create_api_spell("by-the-light-of-the-watchful-moon", "By the Light of the Watchful Moon"),
  APISpell.create_api_spell("call-lightning", "Call Lightning"),
  APISpell.create_api_spell("call-shadow-mastiff", "Call Shadow Mastiff"),
  APISpell.create_api_spell("calm-emotions", "Calm Emotions"),
  APISpell.create_api_spell("calm-of-the-storm", "Calm of the Storm"),
  APISpell.create_api_spell("candles-insight", "Candle’s Insight"),
  APISpell.create_api_spell("carmello-voltas-irksome-preserves", "Carmello-Volta’s Irksome Preserves"),
  APISpell.create_api_spell("catapult", "Catapult"),
  APISpell.create_api_spell("catch-the-breath", "Catch the Breath"),
  APISpell.create_api_spell("caustic-blood", "Caustic Blood"),
  APISpell.create_api_spell("caustic-torrent", "Caustic Torrent"),
  APISpell.create_api_spell("caustic-touch", "Caustic Touch"),
  APISpell.create_api_spell("celebration", "Celebration"),
  APISpell.create_api_spell("chain-lightning", "Chain Lightning"),
  APISpell.create_api_spell("chains-of-torment", "Chains of Torment"),
  APISpell.create_api_spell("chains-of-the-goddess", "Chains of the Goddess"),
  APISpell.create_api_spell("champions-weapon", "Champion’s Weapon"),
  APISpell.create_api_spell("chaotic-form", "Chaotic Form"),
  APISpell.create_api_spell("chaotic-vitality", "Chaotic Vitality"),
  APISpell.create_api_spell("chaotic-world", "Chaotic World"),
  APISpell.create_api_spell("charm-person", "Charm Person"),
  APISpell.create_api_spell("chill-touch", "Chill Touch"),
  APISpell.create_api_spell("chilling-words", "Chilling Words"),
  APISpell.create_api_spell("chronal-lance", "Chronal Lance"),
  APISpell.create_api_spell("circle-of-death", "Circle of Death"),
  APISpell.create_api_spell("circle-of-wind", "Circle of Wind"),
  APISpell.create_api_spell("clairvoyance", "Clairvoyance"),
  APISpell.create_api_spell("clash-of-glaciers", "Clash of Glaciers"),
  APISpell.create_api_spell("claws-of-darkness", "Claws of Darkness"),
  APISpell.create_api_spell("claws-of-the-earth-dragon", "Claws of the Earth Dragon"),
  APISpell.create_api_spell("clearing-the-field", "Clearing the Field"),
  APISpell.create_api_spell("cloak-of-shadow", "Cloak of Shadow"),
  APISpell.create_api_spell("clockwork-bolt", "Clockwork Bolt"),
  APISpell.create_api_spell("clone", "Clone"),
  APISpell.create_api_spell("closing-in", "Closing In"),
  APISpell.create_api_spell("cloudkill", "Cloudkill"),
  APISpell.create_api_spell("cobra-fangs", "Cobra Fangs"),
  APISpell.create_api_spell("color-spray", "Color Spray"),
  APISpell.create_api_spell("command", "Command"),
  APISpell.create_api_spell("commune", "Commune"),
  APISpell.create_api_spell("commune-with-nature", "Commune with Nature"),
  APISpell.create_api_spell("compelled-movement", "Compelled Movement"),
  APISpell.create_api_spell("compelling-fate", "Compelling Fate"),
  APISpell.create_api_spell("comprehend-languages", "Comprehend Languages"),
  APISpell.create_api_spell("comprehend-wild-shape", "Comprehend Wild Shape"),
  APISpell.create_api_spell("compulsion", "Compulsion"),
  APISpell.create_api_spell("cone-of-cold", "Cone of Cold"),
  APISpell.create_api_spell("confound-senses", "Confound Senses"),
  APISpell.create_api_spell("confusion", "Confusion"),
  APISpell.create_api_spell("conjure-animals", "Conjure Animals"),
  APISpell.create_api_spell("conjure-celestial", "Conjure Celestial"),
  APISpell.create_api_spell("conjure-elemental", "Conjure Elemental"),
  APISpell.create_api_spell("conjure-fey", "Conjure Fey"),
  APISpell.create_api_spell("conjure-fey-hound", "Conjure Fey Hound"),
  APISpell.create_api_spell("conjure-forest-defender", "Conjure Forest Defender"),
  APISpell.create_api_spell("conjure-greater-spectral-dead", "Conjure Greater Spectral Dead"),
  APISpell.create_api_spell("conjure-minor-elementals", "Conjure Minor Elementals"),
  APISpell.create_api_spell("conjure-minor-voidborn", "Conjure Minor Voidborn"),
  APISpell.create_api_spell("conjure-scarab-swarm", "Conjure Scarab Swarm"),
  APISpell.create_api_spell("conjure-shadow-titan", "Conjure Shadow Titan"),
  APISpell.create_api_spell("conjure-spectral-dead", "Conjure Spectral Dead"),
  APISpell.create_api_spell("conjure-undead", "Conjure Undead"),
  APISpell.create_api_spell("conjure-voidborn", "Conjure Voidborn"),
  APISpell.create_api_spell("conjure-woodland-beings", "Conjure Woodland Beings"),
  APISpell.create_api_spell("consult-the-storm", "Consult the Storm"),
  APISpell.create_api_spell("contact-other-plane", "Contact Other Plane"),
  APISpell.create_api_spell("contagion", "Contagion"),
  APISpell.create_api_spell("contingency", "Contingency"),
  APISpell.create_api_spell("continual-flame", "Continual Flame"),
  APISpell.create_api_spell("control-water", "Control Water"),
  APISpell.create_api_spell("control-weather", "Control Weather"),
  APISpell.create_api_spell("converse-with-dragon", "Converse With Dragon"),
  APISpell.create_api_spell("costly-victory", "Costly Victory"),
  APISpell.create_api_spell("counterspell", "Counterspell"),
  APISpell.create_api_spell("create-food-and-water", "Create Food and Water"),
  APISpell.create_api_spell("create-ring-servant", "Create Ring Servant"),
  APISpell.create_api_spell("create-thunderstaff", "Create Thunderstaff"),
  APISpell.create_api_spell("create-undead", "Create Undead"),
  APISpell.create_api_spell("create-or-destroy-water", "Create or Destroy Water"),
  APISpell.create_api_spell("creation", "Creation"),
  APISpell.create_api_spell("creeping-ice", "Creeping Ice"),
  APISpell.create_api_spell("crushing-curse", "Crushing Curse"),
  APISpell.create_api_spell("crushing-trample", "Crushing Trample"),
  APISpell.create_api_spell("cure-beast", "Cure Beast"),
  APISpell.create_api_spell("cure-wounds", "Cure Wounds"),
  APISpell.create_api_spell("curse-ring", "Curse Ring"),
  APISpell.create_api_spell("curse-of-boreas", "Curse of Boreas"),
  APISpell.create_api_spell("curse-of-dust", "Curse of Dust"),
  APISpell.create_api_spell("curse-of-incompetence", "Curse of Incompetence"),
  APISpell.create_api_spell("curse-of-yig", "Curse of Yig"),
  APISpell.create_api_spell("curse-of-the-grave", "Curse of the Grave"),
  APISpell.create_api_spell("cursed-gift", "Cursed Gift"),
  APISpell.create_api_spell("cynophobia", "Cynophobia"),
  APISpell.create_api_spell("daggerhawk", "Daggerhawk"),
  APISpell.create_api_spell("dancing-lights", "Dancing Lights"),
  APISpell.create_api_spell("dark-dementing", "Dark Dementing"),
  APISpell.create_api_spell("dark-heraldry", "Dark Heraldry"),
  APISpell.create_api_spell("dark-maw", "Dark Maw"),
  APISpell.create_api_spell("dark-path", "Dark Path"),
  APISpell.create_api_spell("darkbolt", "Darkbolt"),
  APISpell.create_api_spell("darkness", "Darkness"),
  APISpell.create_api_spell("darkvision", "Darkvision"),
  APISpell.create_api_spell("daylight", "Daylight"),
  APISpell.create_api_spell("dead-walking", "Dead Walking"),
  APISpell.create_api_spell("deadly-sting", "Deadly Sting"),
  APISpell.create_api_spell("death-gods-touch", "Death God’s Touch"),
  APISpell.create_api_spell("death-ward", "Death Ward"),
  APISpell.create_api_spell("decay", "Decay"),
  APISpell.create_api_spell("decelerate", "Decelerate"),
  APISpell.create_api_spell("deep-breath", "Deep Breath"),
  APISpell.create_api_spell("defile-healing", "Defile Healing"),
  APISpell.create_api_spell("delay-potion", "Delay Potion"),
  APISpell.create_api_spell("delayed-blast-fireball", "Delayed Blast Fireball"),
  APISpell.create_api_spell("delayed-healing", "Delayed Healing"),
  APISpell.create_api_spell("demiplane", "Demiplane"),
  APISpell.create_api_spell("demon-within", "Demon Within"),
  APISpell.create_api_spell("desiccating-breath", "Desiccating Breath"),
  APISpell.create_api_spell("desolation", "Desolation"),
  APISpell.create_api_spell("destructive-resonance", "Destructive Resonance"),
  APISpell.create_api_spell("detect-dragons", "Detect Dragons"),
  APISpell.create_api_spell("detect-evil-and-good", "Detect Evil and Good"),
  APISpell.create_api_spell("detect-magic", "Detect Magic"),
  APISpell.create_api_spell("detect-poison-and-disease", "Detect Poison and Disease"),
  APISpell.create_api_spell("detect-thoughts", "Detect Thoughts"),
  APISpell.create_api_spell("devas-wings", "Deva’s Wings"),
  APISpell.create_api_spell("dimension-door", "Dimension Door"),
  APISpell.create_api_spell("dimensional-shove", "Dimensional Shove"),
  APISpell.create_api_spell("disguise-self", "Disguise Self"),
  APISpell.create_api_spell("disintegrate", "Disintegrate"),
  APISpell.create_api_spell("dispel-evil-and-good", "Dispel Evil and Good"),
  APISpell.create_api_spell("dispel-magic", "Dispel Magic"),
  APISpell.create_api_spell("disquieting-gaze", "Disquieting Gaze"),
  APISpell.create_api_spell("disruptive-aura", "Disruptive Aura"),
  APISpell.create_api_spell("distracting-divination", "Distracting Divination"),
  APISpell.create_api_spell("distraction-cascade", "Distraction Cascade"),
  APISpell.create_api_spell("divination", "Divination"),
  APISpell.create_api_spell("divine-favor", "Divine Favor"),
  APISpell.create_api_spell("divine-word", "Divine Word"),
  APISpell.create_api_spell("dominate-beast", "Dominate Beast"),
  APISpell.create_api_spell("dominate-monster", "Dominate Monster"),
  APISpell.create_api_spell("dominate-person", "Dominate Person"),
  APISpell.create_api_spell("doom-of-blue-crystal", "Doom of Blue Crystal"),
  APISpell.create_api_spell("doom-of-consuming-fire", "Doom of Consuming Fire"),
  APISpell.create_api_spell("doom-of-dancing-blades", "Doom of Dancing Blades"),
  APISpell.create_api_spell("doom-of-disenchantment", "Doom of Disenchantment"),
  APISpell.create_api_spell("doom-of-serpent-coils", "Doom of Serpent Coils"),
  APISpell.create_api_spell("doom-of-the-cracked-shield", "Doom of the Cracked Shield"),
  APISpell.create_api_spell("doom-of-the-earthen-maw", "Doom of the Earthen Maw"),
  APISpell.create_api_spell("doom-of-the-slippery-rogue", "Doom of the Slippery Rogue"),
  APISpell.create_api_spell("douse-light", "Douse Light"),
  APISpell.create_api_spell("draconic-smite", "Draconic Smite"),
  APISpell.create_api_spell("dragon-breath", "Dragon Breath"),
  APISpell.create_api_spell("dragon-roar", "Dragon Roar"),
  APISpell.create_api_spell("dream", "Dream"),
  APISpell.create_api_spell("drown", "Drown"),
  APISpell.create_api_spell("druidcraft", "Druidcraft"),
  APISpell.create_api_spell("dryads-kiss", "Dryad’s Kiss"),
  APISpell.create_api_spell("earthquake", "Earthquake"),
  APISpell.create_api_spell("earthskimmer", "Earthskimmer"),
  APISpell.create_api_spell("earworm-melody", "Earworm Melody"),
  APISpell.create_api_spell("echoes-of-steel", "Echoes of Steel"),
  APISpell.create_api_spell("ectoplasm", "Ectoplasm"),
  APISpell.create_api_spell("eidetic-memory", "Eidetic Memory"),
  APISpell.create_api_spell("eldritch-blast", "Eldritch Blast"),
  APISpell.create_api_spell("eldritch-communion", "Eldritch Communion"),
  APISpell.create_api_spell("elemental-horns", "Elemental Horns"),
  APISpell.create_api_spell("elemental-twist", "Elemental Twist"),
  APISpell.create_api_spell("emanation-of-yoth", "Emanation of Yoth"),
  APISpell.create_api_spell("enchant-ring", "Enchant Ring"),
  APISpell.create_api_spell("encroaching-shadows", "Encroaching Shadows"),
  APISpell.create_api_spell("encrypt-decrypt", "Encrypt / Decrypt"),
  APISpell.create_api_spell("endow-attribute", "Endow Attribute"),
  APISpell.create_api_spell("energy-absorption", "Energy Absorption"),
  APISpell.create_api_spell("energy-foreknowledge", "Energy Foreknowledge"),
  APISpell.create_api_spell("enhance-ability", "Enhance Ability"),
  APISpell.create_api_spell("enhance-greed", "Enhance Greed"),
  APISpell.create_api_spell("enlargereduce", "Enlarge/Reduce"),
  APISpell.create_api_spell("entangle", "Entangle"),
  APISpell.create_api_spell("enthrall", "Enthrall"),
  APISpell.create_api_spell("entomb", "Entomb"),
  APISpell.create_api_spell("entropic-damage-field", "Entropic Damage Field"),
  APISpell.create_api_spell("essence-instability", "Essence Instability"),
  APISpell.create_api_spell("etherealness", "Etherealness"),
  APISpell.create_api_spell("evercold", "Evercold"),
  APISpell.create_api_spell("expeditious-retreat", "Expeditious Retreat"),
  APISpell.create_api_spell("exsanguinate", "Exsanguinate"),
  APISpell.create_api_spell("exsanguinating-cloud", "Exsanguinating Cloud"),
  APISpell.create_api_spell("extract-knowledge", "Extract Knowledge"),
  APISpell.create_api_spell("eye-bite", "Eye bite"),
  APISpell.create_api_spell("eyebite", "Eyebite"),
  APISpell.create_api_spell("fabricate", "Fabricate"),
  APISpell.create_api_spell("faerie-fire", "Faerie Fire"),
  APISpell.create_api_spell("faithful-hound", "Faithful Hound"),
  APISpell.create_api_spell("false-life", "False Life"),
  APISpell.create_api_spell("fault-line", "Fault Line"),
  APISpell.create_api_spell("fear", "Fear"),
  APISpell.create_api_spell("feather-fall", "Feather Fall"),
  APISpell.create_api_spell("feather-field", "Feather Field"),
  APISpell.create_api_spell("feather-travel", "Feather Travel"),
  APISpell.create_api_spell("feeblemind", "Feeblemind"),
  APISpell.create_api_spell("fey-crown", "Fey Crown"),
  APISpell.create_api_spell("find-familiar", "Find Familiar"),
  APISpell.create_api_spell("find-kin", "Find Kin"),
  APISpell.create_api_spell("find-steed", "Find Steed"),
  APISpell.create_api_spell("find-traps", "Find Traps"),
  APISpell.create_api_spell("find-the-path", "Find the Path"),
  APISpell.create_api_spell("finger-of-death", "Finger of Death"),
  APISpell.create_api_spell("fire-bolt", "Fire Bolt"),
  APISpell.create_api_spell("fire-darts", "Fire Darts"),
  APISpell.create_api_spell("fire-shield", "Fire Shield"),
  APISpell.create_api_spell("fire-storm", "Fire Storm"),
  APISpell.create_api_spell("fire-under-the-tongue", "Fire Under the Tongue"),
  APISpell.create_api_spell("fireball", "Fireball"),
  APISpell.create_api_spell("firewalk", "Firewalk"),
  APISpell.create_api_spell("fist-of-iron", "Fist of Iron"),
  APISpell.create_api_spell("flame-blade", "Flame Blade"),
  APISpell.create_api_spell("flame-strike", "Flame Strike"),
  APISpell.create_api_spell("flame-wave", "Flame Wave"),
  APISpell.create_api_spell("flaming-sphere", "Flaming Sphere"),
  APISpell.create_api_spell("flesh-to-paper", "Flesh to Paper"),
  APISpell.create_api_spell("flesh-to-stone", "Flesh to Stone"),
  APISpell.create_api_spell("flickering-fate", "Flickering Fate"),
  APISpell.create_api_spell("floating-disk", "Floating Disk"),
  APISpell.create_api_spell("fluctuating-alignment", "Fluctuating Alignment"),
  APISpell.create_api_spell("flurry", "Flurry"),
  APISpell.create_api_spell("fly", "Fly"),
  APISpell.create_api_spell("fog-cloud", "Fog Cloud"),
  APISpell.create_api_spell("forbiddance", "Forbiddance"),
  APISpell.create_api_spell("forcecage", "Forcecage"),
  APISpell.create_api_spell("foresight", "Foresight"),
  APISpell.create_api_spell("forest-native", "Forest Native"),
  APISpell.create_api_spell("forest-sanctuary", "Forest Sanctuary"),
  APISpell.create_api_spell("foretell-distraction", "Foretell Distraction"),
  APISpell.create_api_spell("form-of-the-gods", "Form of the Gods"),
  APISpell.create_api_spell("freedom-of-movement", "Freedom of Movement"),
  APISpell.create_api_spell("freeze-blood", "Freeze Blood"),
  APISpell.create_api_spell("freeze-potion", "Freeze Potion"),
  APISpell.create_api_spell("freezing-fog", "Freezing Fog"),
  APISpell.create_api_spell("freezing-sphere", "Freezing Sphere"),
  APISpell.create_api_spell("frenzied-bolt", "Frenzied Bolt"),
  APISpell.create_api_spell("frostbite", "Frostbite"),
  APISpell.create_api_spell("frostbitten-fingers", "Frostbitten Fingers"),
  APISpell.create_api_spell("frozen-razors", "Frozen Razors"),
  APISpell.create_api_spell("furious-hooves", "Furious Hooves"),
  APISpell.create_api_spell("fusillade-of-ice", "Fusillade of Ice"),
  APISpell.create_api_spell("gaseous-form", "Gaseous Form"),
  APISpell.create_api_spell("gate", "Gate"),
  APISpell.create_api_spell("gear-barrage", "Gear Barrage"),
  APISpell.create_api_spell("geas", "Geas"),
  APISpell.create_api_spell("gentle-repose", "Gentle Repose"),
  APISpell.create_api_spell("ghoul-kings-cloak", "Ghoul King’s Cloak"),
  APISpell.create_api_spell("giant-insect", "Giant Insect"),
  APISpell.create_api_spell("gird-the-spirit", "Gird the Spirit"),
  APISpell.create_api_spell("glacial-cascade", "Glacial Cascade"),
  APISpell.create_api_spell("glacial-fog", "Glacial Fog"),
  APISpell.create_api_spell("glibness", "Glibness"),
  APISpell.create_api_spell("gliding-step", "Gliding Step"),
  APISpell.create_api_spell("glimpse-of-the-void", "Glimpse of the Void"),
  APISpell.create_api_spell("globe-of-invulnerability", "Globe of Invulnerability"),
  APISpell.create_api_spell("gloomwrought-barrier", "Gloomwrought Barrier"),
  APISpell.create_api_spell("gluey-globule", "Gluey Globule"),
  APISpell.create_api_spell("glyph-of-shifting", "Glyph of Shifting"),
  APISpell.create_api_spell("glyph-of-warding", "Glyph of Warding"),
  APISpell.create_api_spell("goats-hoof-charm", "Goat's Hoof Charm"),
  APISpell.create_api_spell("going-in-circles", "Going in Circles"),
  APISpell.create_api_spell("goodberry", "Goodberry"),
  APISpell.create_api_spell("gordolays-pleasant-aroma", "Gordolay’s Pleasant Aroma"),
  APISpell.create_api_spell("grasp-of-the-tupilak", "Grasp of the Tupilak"),
  APISpell.create_api_spell("grease", "Grease"),
  APISpell.create_api_spell("greater-invisibility", "Greater Invisibility"),
  APISpell.create_api_spell("greater-maze", "Greater Maze"),
  APISpell.create_api_spell("greater-restoration", "Greater Restoration"),
  APISpell.create_api_spell("greater-seal-of-sanctuary", "Greater Seal of Sanctuary"),
  APISpell.create_api_spell("green-decay", "Green Decay"),
  APISpell.create_api_spell("grudge-match", "Grudge Match"),
  APISpell.create_api_spell("guardian-of-faith", "Guardian of Faith"),
  APISpell.create_api_spell("guards-and-wards", "Guards and Wards"),
  APISpell.create_api_spell("guest-of-honor", "Guest of Honor"),
  APISpell.create_api_spell("guidance", "Guidance"),
  APISpell.create_api_spell("guiding-bolt", "Guiding Bolt"),
  APISpell.create_api_spell("guiding-star", "Guiding Star"),
  APISpell.create_api_spell("gust-of-wind", "Gust of Wind"),
  APISpell.create_api_spell("hallow", "Hallow"),
  APISpell.create_api_spell("hallucinatory-terrain", "Hallucinatory Terrain"),
  APISpell.create_api_spell("hamstring", "Hamstring"),
  APISpell.create_api_spell("hard-heart", "Hard Heart"),
  APISpell.create_api_spell("harm", "Harm"),
  APISpell.create_api_spell("harry", "Harry"),
  APISpell.create_api_spell("harrying-hounds", "Harrying Hounds"),
  APISpell.create_api_spell("harsh-light-of-summers-glare", "Harsh Light of Summer’s Glare"),
  APISpell.create_api_spell("haste", "Haste"),
  APISpell.create_api_spell("heal", "Heal"),
  APISpell.create_api_spell("healing-word", "Healing Word"),
  APISpell.create_api_spell("heart-to-heart", "Heart to Heart"),
  APISpell.create_api_spell("heart-seeking-arrow", "Heart-Seeking Arrow"),
  APISpell.create_api_spell("heartache", "Heartache"),
  APISpell.create_api_spell("heartstop", "Heartstop"),
  APISpell.create_api_spell("heartstrike", "Heartstrike"),
  APISpell.create_api_spell("heat-metal", "Heat Metal"),
  APISpell.create_api_spell("heavenly-crown", "Heavenly Crown"),
  APISpell.create_api_spell("hedrens-birds-of-clay", "Hedren’s Birds of Clay"),
  APISpell.create_api_spell("hellish-rebuke", "Hellish Rebuke"),
  APISpell.create_api_spell("hematomancy", "Hematomancy"),
  APISpell.create_api_spell("heros-steel", "Hero's Steel"),
  APISpell.create_api_spell("heroes-feast", "Heroes' Feast"),
  APISpell.create_api_spell("heroism", "Heroism"),
  APISpell.create_api_spell("hide-in-ones-shadow", "Hide in One’s Shadow"),
  APISpell.create_api_spell("hideous-laughter", "Hideous Laughter"),
  APISpell.create_api_spell("hoarfrost", "Hoarfrost"),
  APISpell.create_api_spell("hobble", "Hobble"),
  APISpell.create_api_spell("hobble-mount", "Hobble Mount"),
  APISpell.create_api_spell("hold-monster", "Hold Monster"),
  APISpell.create_api_spell("hold-person", "Hold Person"),
  APISpell.create_api_spell("holy-aura", "Holy Aura"),
  APISpell.create_api_spell("holy-ground", "Holy Ground"),
  APISpell.create_api_spell("hone-blade", "Hone Blade"),
  APISpell.create_api_spell("hunger-of-leng", "Hunger of Leng"),
  APISpell.create_api_spell("hunters-mark", "Hunter's Mark"),
  APISpell.create_api_spell("hunters-endurance", "Hunter’s Endurance"),
  APISpell.create_api_spell("hunting-stand", "Hunting Stand"),
  APISpell.create_api_spell("hypnotic-pattern", "Hypnotic Pattern"),
  APISpell.create_api_spell("ice-fortress", "Ice Fortress"),
  APISpell.create_api_spell("ice-hammer", "Ice Hammer"),
  APISpell.create_api_spell("ice-soldiers", "Ice Soldiers"),
  APISpell.create_api_spell("ice-storm", "Ice Storm"),
  APISpell.create_api_spell("icicle-daggers", "Icicle Daggers"),
  APISpell.create_api_spell("icy-grasp-of-the-void", "Icy Grasp of the Void"),
  APISpell.create_api_spell("icy-manipulation", "Icy Manipulation"),
  APISpell.create_api_spell("identify", "Identify"),
  APISpell.create_api_spell("ill-fated-word", "Ill-Fated Word"),
  APISpell.create_api_spell("illuminate-spoor", "Illuminate Spoor"),
  APISpell.create_api_spell("illusory-script", "Illusory Script"),
  APISpell.create_api_spell("impending-ally", "Impending Ally"),
  APISpell.create_api_spell("imprisonment", "Imprisonment"),
  APISpell.create_api_spell("incendiary-cloud", "Incendiary Cloud"),
  APISpell.create_api_spell("inflict-wounds", "Inflict Wounds"),
  APISpell.create_api_spell("innocuous-aspect", "Innocuous Aspect"),
  APISpell.create_api_spell("insect-plague", "Insect Plague"),
  APISpell.create_api_spell("insightful-maneuver", "Insightful Maneuver"),
  APISpell.create_api_spell("inspiring-speech", "Inspiring Speech"),
  APISpell.create_api_spell("instant-fortification", "Instant Fortification"),
  APISpell.create_api_spell("instant-siege-weapon", "Instant Siege Weapon"),
  APISpell.create_api_spell("instant-snare", "Instant Snare"),
  APISpell.create_api_spell("instant-summons", "Instant Summons"),
  APISpell.create_api_spell("invisibility", "Invisibility"),
  APISpell.create_api_spell("ire-of-the-mountain", "Ire of the Mountain"),
  APISpell.create_api_spell("iron-hand", "Iron Hand"),
  APISpell.create_api_spell("irresistible-dance", "Irresistible Dance"),
  APISpell.create_api_spell("jump", "Jump"),
  APISpell.create_api_spell("kareefs-entreaty", "Kareef’s Entreaty"),
  APISpell.create_api_spell("keening-wail", "Keening Wail"),
  APISpell.create_api_spell("killing-fields", "Killing Fields"),
  APISpell.create_api_spell("kiss-of-the-succubus", "Kiss of the Succubus"),
  APISpell.create_api_spell("knock", "Knock"),
  APISpell.create_api_spell("kobolds-fury", "Kobold’s Fury"),
  APISpell.create_api_spell("labyrinth-mastery", "Labyrinth Mastery"),
  APISpell.create_api_spell("labyrinthine-howl", "Labyrinthine Howl"),
  APISpell.create_api_spell("lacerate", "Lacerate"),
  APISpell.create_api_spell("lair-sense", "Lair Sense"),
  APISpell.create_api_spell("last-rays-of-the-dying-sun", "Last Rays of the Dying Sun"),
  APISpell.create_api_spell("lava-stone", "Lava Stone"),
  APISpell.create_api_spell("lay-to-rest", "Lay to Rest"),
  APISpell.create_api_spell("legend-killer", "Legend Killer"),
  APISpell.create_api_spell("legend-lore", "Legend Lore"),
  APISpell.create_api_spell("legion", "Legion"),
  APISpell.create_api_spell("legion-of-rabid-squirrels", "Legion of Rabid Squirrels"),
  APISpell.create_api_spell("lesser-maze", "Lesser Maze"),
  APISpell.create_api_spell("lesser-restoration", "Lesser Restoration"),
  APISpell.create_api_spell("levitate", "Levitate"),
  APISpell.create_api_spell("life-drain", "Life Drain"),
  APISpell.create_api_spell("life-hack", "Life Hack"),
  APISpell.create_api_spell("life-sense", "Life Sense"),
  APISpell.create_api_spell("life-transference-arrow", "Life Transference Arrow"),
  APISpell.create_api_spell("life-from-death", "Life from Death"),
  APISpell.create_api_spell("light", "Light"),
  APISpell.create_api_spell("lightning-bolt", "Lightning Bolt"),
  APISpell.create_api_spell("litany-of-sure-hands", "Litany of Sure Hands"),
  APISpell.create_api_spell("living-shadows", "Living Shadows"),
  APISpell.create_api_spell("locate-animals-or-plants", "Locate Animals or Plants"),
  APISpell.create_api_spell("locate-creature", "Locate Creature"),
  APISpell.create_api_spell("locate-object", "Locate Object"),
  APISpell.create_api_spell("lock-armor", "Lock Armor"),
  APISpell.create_api_spell("longstrider", "Longstrider"),
  APISpell.create_api_spell("looping-trail", "Looping Trail"),
  APISpell.create_api_spell("lovesick", "Lovesick"),
  APISpell.create_api_spell("maddening-whispers", "Maddening Whispers"),
  APISpell.create_api_spell("mage-armor", "Mage Armor"),
  APISpell.create_api_spell("mage-hand", "Mage Hand"),
  APISpell.create_api_spell("magic-circle", "Magic Circle"),
  APISpell.create_api_spell("magic-jar", "Magic Jar"),
  APISpell.create_api_spell("magic-missile", "Magic Missile"),
  APISpell.create_api_spell("magic-mouth", "Magic Mouth"),
  APISpell.create_api_spell("magic-weapon", "Magic Weapon"),
  APISpell.create_api_spell("magnificent-mansion", "Magnificent Mansion"),
  APISpell.create_api_spell("maim", "Maim"),
  APISpell.create_api_spell("major-image", "Major Image"),
  APISpell.create_api_spell("malevolent-waves", "Malevolent Waves"),
  APISpell.create_api_spell("mammons-due", "Mammon’s Due"),
  APISpell.create_api_spell("mark-prey", "Mark Prey"),
  APISpell.create_api_spell("mass-cure-wounds", "Mass Cure Wounds"),
  APISpell.create_api_spell("mass-heal", "Mass Heal"),
  APISpell.create_api_spell("mass-healing-word", "Mass Healing Word"),
  APISpell.create_api_spell("mass-hobble-mount", "Mass Hobble Mount"),
  APISpell.create_api_spell("mass-suggestion", "Mass Suggestion"),
  APISpell.create_api_spell("mass-surge-dampener", "Mass Surge Dampener"),
  APISpell.create_api_spell("maw-of-needles", "Maw of Needles"),
  APISpell.create_api_spell("maze", "Maze"),
  APISpell.create_api_spell("meld-into-stone", "Meld into Stone"),
  APISpell.create_api_spell("memento-mori", "Memento Mori"),
  APISpell.create_api_spell("mending", "Mending"),
  APISpell.create_api_spell("mephitic-croak", "Mephitic Croak"),
  APISpell.create_api_spell("message", "Message"),
  APISpell.create_api_spell("meteor-swarm", "Meteor Swarm"),
  APISpell.create_api_spell("mind-blank", "Mind Blank"),
  APISpell.create_api_spell("mind-exchange", "Mind Exchange"),
  APISpell.create_api_spell("minor-illusion", "Minor Illusion"),
  APISpell.create_api_spell("mirage-arcane", "Mirage Arcane"),
  APISpell.create_api_spell("mire", "Mire"),
  APISpell.create_api_spell("mirror-image", "Mirror Image"),
  APISpell.create_api_spell("mislead", "Mislead"),
  APISpell.create_api_spell("misstep", "Misstep"),
  APISpell.create_api_spell("mist-of-wonders", "Mist of Wonders"),
  APISpell.create_api_spell("misty-step", "Misty Step"),
  APISpell.create_api_spell("modify-memory", "Modify Memory"),
  APISpell.create_api_spell("monstrous-empathy", "Monstrous Empathy"),
  APISpell.create_api_spell("moon-trap", "Moon Trap"),
  APISpell.create_api_spell("moonbeam", "Moonbeam"),
  APISpell.create_api_spell("mosquito-bane", "Mosquito Bane"),
  APISpell.create_api_spell("move-earth", "Move Earth"),
  APISpell.create_api_spell("mud-pack", "Mud Pack"),
  APISpell.create_api_spell("negative-image", "Negative Image"),
  APISpell.create_api_spell("nether-weapon", "Nether Weapon"),
  APISpell.create_api_spell("night-terrors", "Night Terrors"),
  APISpell.create_api_spell("nightfall", "Nightfall"),
  APISpell.create_api_spell("nip-at-the-heels", "Nip at the Heels"),
  APISpell.create_api_spell("nondetection", "Nondetection"),
  APISpell.create_api_spell("not-dead-yet", "Not Dead Yet"),
  APISpell.create_api_spell("not-this-day", "Not This Day!"),
  APISpell.create_api_spell("orb-of-light", "Orb of Light"),
  APISpell.create_api_spell("outflanking-boon", "Outflanking Boon"),
  APISpell.create_api_spell("paragon-of-chaos", "Paragon of Chaos"),
  APISpell.create_api_spell("pass-without-trace", "Pass without Trace"),
  APISpell.create_api_spell("passwall", "Passwall"),
  APISpell.create_api_spell("pendulum", "Pendulum"),
  APISpell.create_api_spell("phantasmal-killer", "Phantasmal Killer"),
  APISpell.create_api_spell("phantom-dragon", "Phantom Dragon"),
  APISpell.create_api_spell("phantom-steed", "Phantom Steed"),
  APISpell.create_api_spell("pitfall", "Pitfall"),
  APISpell.create_api_spell("planar-ally", "Planar Ally"),
  APISpell.create_api_spell("planar-binding", "Planar Binding"),
  APISpell.create_api_spell("plane-shift", "Plane Shift"),
  APISpell.create_api_spell("plant-growth", "Plant Growth"),
  APISpell.create_api_spell("poison-spray", "Poison Spray"),
  APISpell.create_api_spell("poisoned-volley", "Poisoned Volley"),
  APISpell.create_api_spell("polymorph", "Polymorph"),
  APISpell.create_api_spell("potency-of-the-pack", "Potency of the Pack"),
  APISpell.create_api_spell("power-word-kill", "Power Word Kill"),
  APISpell.create_api_spell("power-word-kneel", "Power Word Kneel"),
  APISpell.create_api_spell("power-word-pain", "Power Word Pain"),
  APISpell.create_api_spell("power-word-stun", "Power Word Stun"),
  APISpell.create_api_spell("prayer-of-healing", "Prayer of Healing"),
  APISpell.create_api_spell("prestidigitation", "Prestidigitation"),
  APISpell.create_api_spell("primal-infusion", "Primal Infusion"),
  APISpell.create_api_spell("prismatic-ray", "Prismatic Ray"),
  APISpell.create_api_spell("prismatic-spray", "Prismatic Spray"),
  APISpell.create_api_spell("prismatic-wall", "Prismatic Wall"),
  APISpell.create_api_spell("private-sanctum", "Private Sanctum"),
  APISpell.create_api_spell("produce-flame", "Produce Flame"),
  APISpell.create_api_spell("programmed-illusion", "Programmed Illusion"),
  APISpell.create_api_spell("project-image", "Project Image"),
  APISpell.create_api_spell("protection-from-energy", "Protection from Energy"),
  APISpell.create_api_spell("protection-from-evil-and-good", "Protection from Evil and Good"),
  APISpell.create_api_spell("protection-from-poison", "Protection from Poison"),
  APISpell.create_api_spell("protection-from-the-void", "Protection from the Void"),
  APISpell.create_api_spell("protective-ice", "Protective Ice"),
  APISpell.create_api_spell("puff-of-smoke", "Puff of Smoke"),
  APISpell.create_api_spell("pummelstone", "Pummelstone"),
  APISpell.create_api_spell("purify-food-and-drink", "Purify Food and Drink"),
  APISpell.create_api_spell("pyroclasm", "Pyroclasm"),
  APISpell.create_api_spell("quick-time", "Quick Time"),
  APISpell.create_api_spell("quicken", "Quicken"),
  APISpell.create_api_spell("quicksilver-mantle", "Quicksilver Mantle"),
  APISpell.create_api_spell("quintessence", "Quintessence"),
  APISpell.create_api_spell("raid-the-lair", "Raid the Lair"),
  APISpell.create_api_spell("rain-of-blades", "Rain of Blades"),
  APISpell.create_api_spell("raise-dead", "Raise Dead"),
  APISpell.create_api_spell("ray-of-alchemical-negation", "Ray of Alchemical Negation"),
  APISpell.create_api_spell("ray-of-enfeeblement", "Ray of Enfeeblement"),
  APISpell.create_api_spell("ray-of-frost", "Ray of Frost"),
  APISpell.create_api_spell("ray-of-life-suppression", "Ray of Life Suppression"),
  APISpell.create_api_spell("ray-of-sickness", "Ray of Sickness"),
  APISpell.create_api_spell("reaver-spirit", "Reaver Spirit"),
  APISpell.create_api_spell("regenerate", "Regenerate"),
  APISpell.create_api_spell("reincarnate", "Reincarnate"),
  APISpell.create_api_spell("remove-curse", "Remove Curse"),
  APISpell.create_api_spell("reposition", "Reposition"),
  APISpell.create_api_spell("reset", "Reset"),
  APISpell.create_api_spell("resilient-sphere", "Resilient Sphere"),
  APISpell.create_api_spell("resistance", "Resistance"),
  APISpell.create_api_spell("resurrection", "Resurrection"),
  APISpell.create_api_spell("reverberate", "Reverberate"),
  APISpell.create_api_spell("reverse-gravity", "Reverse Gravity"),
  APISpell.create_api_spell("revive-beast", "Revive Beast"),
  APISpell.create_api_spell("revivify", "Revivify"),
  APISpell.create_api_spell("right-the-stars", "Right the Stars"),
  APISpell.create_api_spell("ring-strike", "Ring Strike"),
  APISpell.create_api_spell("ring-ward", "Ring Ward"),
  APISpell.create_api_spell("riptide", "Riptide"),
  APISpell.create_api_spell("rolling-thunder", "Rolling Thunder"),
  APISpell.create_api_spell("rope-trick", "Rope Trick"),
  APISpell.create_api_spell("rotting-corpse", "Rotting Corpse"),
  APISpell.create_api_spell("rune-of-imprisonment", "Rune of Imprisonment"),
  APISpell.create_api_spell("sacred-flame", "Sacred Flame"),
  APISpell.create_api_spell("salt-lash", "Salt Lash"),
  APISpell.create_api_spell("sanctuary", "Sanctuary"),
  APISpell.create_api_spell("sand-ship", "Sand Ship"),
  APISpell.create_api_spell("sanguine-horror", "Sanguine Horror"),
  APISpell.create_api_spell("scale-rot", "Scale Rot"),
  APISpell.create_api_spell("scentless", "Scentless"),
  APISpell.create_api_spell("scorching-ray", "Scorching Ray"),
  APISpell.create_api_spell("screaming-ray", "Screaming Ray"),
  APISpell.create_api_spell("scribe", "Scribe"),
  APISpell.create_api_spell("scry-ambush", "Scry Ambush"),
  APISpell.create_api_spell("scrying", "Scrying"),
  APISpell.create_api_spell("sculpt-snow", "Sculpt Snow"),
  APISpell.create_api_spell("seal-of-sanctuary", "Seal of Sanctuary"),
  APISpell.create_api_spell("searing-sun", "Searing Sun"),
  APISpell.create_api_spell("secret-chest", "Secret Chest"),
  APISpell.create_api_spell("see-beyond", "See Beyond"),
  APISpell.create_api_spell("see-invisibility", "See Invisibility"),
  APISpell.create_api_spell("seed-of-destruction", "Seed of Destruction"),
  APISpell.create_api_spell("seeming", "Seeming"),
  APISpell.create_api_spell("seeping-death", "Seeping Death"),
  APISpell.create_api_spell("seers-reaction", "Seer’s Reaction"),
  APISpell.create_api_spell("semblance-of-dread", "Semblance of Dread"),
  APISpell.create_api_spell("sending", "Sending"),
  APISpell.create_api_spell("sequester", "Sequester"),
  APISpell.create_api_spell("shade", "Shade"),
  APISpell.create_api_spell("shadow-armor", "Shadow Armor"),
  APISpell.create_api_spell("shadow-bite", "Shadow Bite"),
  APISpell.create_api_spell("shadow-blindness", "Shadow Blindness"),
  APISpell.create_api_spell("shadow-hands", "Shadow Hands"),
  APISpell.create_api_spell("shadow-monsters", "Shadow Monsters"),
  APISpell.create_api_spell("shadow-puppets", "Shadow Puppets"),
  APISpell.create_api_spell("shadow-trove", "Shadow Trove"),
  APISpell.create_api_spell("shadows-brought-to-light", "Shadows Brought to Light"),
  APISpell.create_api_spell("shadowy-retribution", "Shadowy Retribution"),
  APISpell.create_api_spell("shapechange", "Shapechange"),
  APISpell.create_api_spell("shared-sacrifice", "Shared Sacrifice"),
  APISpell.create_api_spell("shatter", "Shatter"),
  APISpell.create_api_spell("sheen-of-ice", "Sheen of Ice"),
  APISpell.create_api_spell("shield", "Shield"),
  APISpell.create_api_spell("shield-of-faith", "Shield of Faith"),
  APISpell.create_api_spell("shifting-the-odds", "Shifting the Odds"),
  APISpell.create_api_spell("shillelagh", "Shillelagh"),
  APISpell.create_api_spell("shiver", "Shiver"),
  APISpell.create_api_spell("shocking-grasp", "Shocking Grasp"),
  APISpell.create_api_spell("shroud-of-death", "Shroud of Death"),
  APISpell.create_api_spell("sidestep-arrow", "Sidestep Arrow"),
  APISpell.create_api_spell("sign-of-koth", "Sign of Koth"),
  APISpell.create_api_spell("silence", "Silence"),
  APISpell.create_api_spell("silent-image", "Silent Image"),
  APISpell.create_api_spell("silhouette", "Silhouette"),
  APISpell.create_api_spell("simulacrum", "Simulacrum"),
  APISpell.create_api_spell("sir-mittinzs-move-curse", "Sir Mittinz’s Move Curse"),
  APISpell.create_api_spell("sleep", "Sleep"),
  APISpell.create_api_spell("sleep-of-the-deep", "Sleep of the Deep"),
  APISpell.create_api_spell("sleet-storm", "Sleet Storm"),
  APISpell.create_api_spell("slippery-fingers", "Slippery Fingers"),
  APISpell.create_api_spell("slither", "Slither"),
  APISpell.create_api_spell("slow", "Slow"),
  APISpell.create_api_spell("snow-boulder", "Snow Boulder"),
  APISpell.create_api_spell("snow-fort", "Snow Fort"),
  APISpell.create_api_spell("snowy-coat", "Snowy Coat"),
  APISpell.create_api_spell("song-of-the-forest", "Song of the Forest"),
  APISpell.create_api_spell("spare-the-dying", "Spare the Dying"),
  APISpell.create_api_spell("speak-with-animals", "Speak with Animals"),
  APISpell.create_api_spell("speak-with-dead", "Speak with Dead"),
  APISpell.create_api_spell("speak-with-inanimate-object", "Speak with Inanimate Object"),
  APISpell.create_api_spell("speak-with-plants", "Speak with Plants"),
  APISpell.create_api_spell("spider-climb", "Spider Climb"),
  APISpell.create_api_spell("spike-growth", "Spike Growth"),
  APISpell.create_api_spell("spin", "Spin"),
  APISpell.create_api_spell("spinning-axes", "Spinning Axes"),
  APISpell.create_api_spell("spirit-guardians", "Spirit Guardians"),
  APISpell.create_api_spell("spiritual-weapon", "Spiritual Weapon"),
  APISpell.create_api_spell("spiteful-weapon", "Spiteful Weapon"),
  APISpell.create_api_spell("spur-mount", "Spur Mount"),
  APISpell.create_api_spell("staff-of-violet-fire", "Staff of Violet Fire"),
  APISpell.create_api_spell("stanch", "Stanch"),
  APISpell.create_api_spell("stars-heart", "Star's Heart"),
  APISpell.create_api_spell("starburst", "Starburst"),
  APISpell.create_api_spell("starfall", "Starfall"),
  APISpell.create_api_spell("starry-vision", "Starry Vision"),
  APISpell.create_api_spell("steal-warmth", "Steal Warmth"),
  APISpell.create_api_spell("steam-blast", "Steam Blast"),
  APISpell.create_api_spell("steam-whistle", "Steam Whistle"),
  APISpell.create_api_spell("stench-of-rot", "Stench of Rot"),
  APISpell.create_api_spell("stinking-cloud", "Stinking Cloud"),
  APISpell.create_api_spell("stone-shape", "Stone Shape"),
  APISpell.create_api_spell("stoneskin", "Stoneskin"),
  APISpell.create_api_spell("storm-of-vengeance", "Storm of Vengeance"),
  APISpell.create_api_spell("storm-of-wings", "Storm of Wings"),
  APISpell.create_api_spell("sudden-dawn", "Sudden Dawn"),
  APISpell.create_api_spell("suggestion", "Suggestion"),
  APISpell.create_api_spell("summon-eldritch-servitor", "Summon Eldritch Servitor"),
  APISpell.create_api_spell("summon-star", "Summon Star"),
  APISpell.create_api_spell("sunbeam", "Sunbeam"),
  APISpell.create_api_spell("sunburst", "Sunburst"),
  APISpell.create_api_spell("surge-dampener", "Surge Dampener"),
  APISpell.create_api_spell("surprise-blessing", "Surprise Blessing"),
  APISpell.create_api_spell("symbol", "Symbol"),
  APISpell.create_api_spell("symbol-of-sorcery", "Symbol of Sorcery"),
  APISpell.create_api_spell("talons-of-a-hungry-land", "Talons of a Hungry Land"),
  APISpell.create_api_spell("targeting-foreknowledge", "Targeting Foreknowledge"),
  APISpell.create_api_spell("telekinesis", "Telekinesis"),
  APISpell.create_api_spell("telepathic-bond", "Telepathic Bond"),
  APISpell.create_api_spell("teleport", "Teleport"),
  APISpell.create_api_spell("teleportation-circle", "Teleportation Circle"),
  APISpell.create_api_spell("thaumaturgy", "Thaumaturgy"),
  APISpell.create_api_spell("thin-the-ice", "Thin the Ice"),
  APISpell.create_api_spell("thousand-darts", "Thousand Darts"),
  APISpell.create_api_spell("throes-of-ecstasy", "Throes of Ecstasy"),
  APISpell.create_api_spell("thunder-bolt", "Thunder Bolt"),
  APISpell.create_api_spell("thunderclap", "Thunderclap"),
  APISpell.create_api_spell("thunderous-charge", "Thunderous Charge"),
  APISpell.create_api_spell("thunderous-stampede", "Thunderous Stampede"),
  APISpell.create_api_spell("thunderous-wave", "Thunderous Wave"),
  APISpell.create_api_spell("thunderstorm", "Thunderstorm"),
  APISpell.create_api_spell("thunderwave", "Thunderwave"),
  APISpell.create_api_spell("tidal-barrier", "Tidal Barrier"),
  APISpell.create_api_spell("time-jump", "Time Jump"),
  APISpell.create_api_spell("time-loop", "Time Loop"),
  APISpell.create_api_spell("time-slippage", "Time Slippage"),
  APISpell.create_api_spell("time-step", "Time Step"),
  APISpell.create_api_spell("time-stop", "Time Stop"),
  APISpell.create_api_spell("time-vortex", "Time Vortex"),
  APISpell.create_api_spell("time-in-a-bottle", "Time in a Bottle"),
  APISpell.create_api_spell("timely-distraction", "Timely Distraction"),
  APISpell.create_api_spell("tiny-hut", "Tiny Hut"),
  APISpell.create_api_spell("tireless", "Tireless"),
  APISpell.create_api_spell("tongue-tied", "Tongue Tied"),
  APISpell.create_api_spell("tongue-of-sand", "Tongue of Sand"),
  APISpell.create_api_spell("tongues", "Tongues"),
  APISpell.create_api_spell("torrent-of-fire", "Torrent of Fire"),
  APISpell.create_api_spell("touch-of-the-unliving", "Touch of the Unliving"),
  APISpell.create_api_spell("tracer", "Tracer"),
  APISpell.create_api_spell("transport-via-plants", "Transport via Plants"),
  APISpell.create_api_spell("treasure-chasm", "Treasure Chasm"),
  APISpell.create_api_spell("tree-heal", "Tree Heal"),
  APISpell.create_api_spell("tree-running", "Tree Running"),
  APISpell.create_api_spell("tree-speak", "Tree Speak"),
  APISpell.create_api_spell("tree-stride", "Tree Stride"),
  APISpell.create_api_spell("trench", "Trench"),
  APISpell.create_api_spell("trick-question", "Trick Question"),
  APISpell.create_api_spell("triumph-of-ice", "Triumph of Ice"),
  APISpell.create_api_spell("true-polymorph", "True Polymorph"),
  APISpell.create_api_spell("true-resurrection", "True Resurrection"),
  APISpell.create_api_spell("true-seeing", "True Seeing"),
  APISpell.create_api_spell("true-strike", "True Strike"),
  APISpell.create_api_spell("twist-the-skein", "Twist the Skein"),
  APISpell.create_api_spell("umbral-storm", "Umbral Storm"),
  APISpell.create_api_spell("uncontrollable-transformation", "Uncontrollable Transformation"),
  APISpell.create_api_spell("undermine-armor", "Undermine Armor"),
  APISpell.create_api_spell("unholy-defiance", "Unholy Defiance"),
  APISpell.create_api_spell("unleash-effigy", "Unleash Effigy"),
  APISpell.create_api_spell("unluck-on-that", "Unluck On That"),
  APISpell.create_api_spell("unseen-servant", "Unseen Servant"),
  APISpell.create_api_spell("unseen-strangler", "Unseen Strangler"),
  APISpell.create_api_spell("vampiric-touch", "Vampiric Touch"),
  APISpell.create_api_spell("vicious-mockery", "Vicious Mockery"),
  APISpell.create_api_spell("vine-trestle", "Vine Trestle"),
  APISpell.create_api_spell("visage-of-madness", "Visage of Madness"),
  APISpell.create_api_spell("vital-mark", "Vital Mark"),
  APISpell.create_api_spell("void-rift", "Void Rift"),
  APISpell.create_api_spell("void-strike", "Void Strike"),
  APISpell.create_api_spell("volley-shield", "Volley Shield"),
  APISpell.create_api_spell("vomit-tentacles", "Vomit Tentacles"),
  APISpell.create_api_spell("voorish-sign", "Voorish Sign"),
  APISpell.create_api_spell("waft", "Waft"),
  APISpell.create_api_spell("walk-the-twisted-path", "Walk the Twisted Path"),
  APISpell.create_api_spell("walking-wall", "Walking Wall"),
  APISpell.create_api_spell("wall-of-fire", "Wall of Fire"),
  APISpell.create_api_spell("wall-of-force", "Wall of Force"),
  APISpell.create_api_spell("wall-of-ice", "Wall of Ice"),
  APISpell.create_api_spell("wall-of-stone", "Wall of Stone"),
  APISpell.create_api_spell("wall-of-thorns", "Wall of Thorns"),
  APISpell.create_api_spell("wall-of-time", "Wall of Time"),
  APISpell.create_api_spell("warding-bond", "Warding Bond"),
  APISpell.create_api_spell("warning-shout", "Warning Shout"),
  APISpell.create_api_spell("warp-mind-and-matter", "Warp Mind and Matter"),
  APISpell.create_api_spell("water-breathing", "Water Breathing"),
  APISpell.create_api_spell("water-walk", "Water Walk"),
  APISpell.create_api_spell("weapon-of-blood", "Weapon of Blood"),
  APISpell.create_api_spell("web", "Web"),
  APISpell.create_api_spell("weilers-ward", "Weiler’s Ward"),
  APISpell.create_api_spell("weird", "Weird"),
  APISpell.create_api_spell("wild-shield", "Wild Shield"),
  APISpell.create_api_spell("wind-lash", "Wind Lash"),
  APISpell.create_api_spell("wind-tunnel", "Wind Tunnel"),
  APISpell.create_api_spell("wind-walk", "Wind Walk"),
  APISpell.create_api_spell("wind-wall", "Wind Wall"),
  APISpell.create_api_spell("wind-of-the-hereafter", "Wind of the Hereafter"),
  APISpell.create_api_spell("winters-radiance", "Winter's Radiance"),
  APISpell.create_api_spell("winterdark", "Winterdark"),
  APISpell.create_api_spell("wintry-glide", "Wintry Glide"),
  APISpell.create_api_spell("wish", "Wish"),
  APISpell.create_api_spell("withered-sight", "Withered Sight"),
  APISpell.create_api_spell("wolfsong", "Wolfsong"),
  APISpell.create_api_spell("word-of-misfortune", "Word of Misfortune"),
  APISpell.create_api_spell("word-of-recall", "Word of Recall"),
  APISpell.create_api_spell("wresting-wind", "Wresting Wind"),
  APISpell.create_api_spell("writhing-arms", "Writhing Arms"),
  APISpell.create_api_spell("yellow-sign", "Yellow Sign"),
  APISpell.create_api_spell("zone-of-truth", "Zone of Truth"),

  # weapon categories
  WeaponCategory(name='Simple Melee Weapons'), 
  WeaponCategory(name='Simple Ranged Weapons'), 
  WeaponCategory(name='Martial Melee Weapons'), 
  WeaponCategory(name='Martial Ranged Weapons'),

  # damage types
  DamageType(name='bludgeoning'),
  DamageType(name='piercing'),
  DamageType(name='slashing'),
  DamageType(name='acid'),
  DamageType(name='poison'),
  DamageType(name='fire'),
  DamageType(name='cold'),
  DamageType(name='force'),
  DamageType(name='lightning'),
  DamageType(name='thunder'),
  DamageType(name='necrotic'),
  DamageType(name='psychic'),
  DamageType(name='radiant'),

  # weapon properties (need to enable adding more)
  WeaponProperty(name='ammunition (range 30/120)'),
  WeaponProperty(name='ammunition (range 25/100)'),
  WeaponProperty(name='ammunition (range 100/400)'),
  WeaponProperty(name='ammunition (range 150/600)'),
  WeaponProperty(name='finesse'),
  WeaponProperty(name='heavy'),
  WeaponProperty(name='light'),
  WeaponProperty(name='loading'),
  WeaponProperty(name='reach'),
  WeaponProperty(name='special'),
  WeaponProperty(name='thrown (range 5/15)'),
  WeaponProperty(name='thrown (range 20/60)'),
  WeaponProperty(name='thrown (range 30/120)'),
  WeaponProperty(name='two-handed'),
  WeaponProperty(name='versatile (1d8)'),
  WeaponProperty(name='versatile (1d10)'),

  # magic schools
  MagicSchool(name='illusion'),
  MagicSchool(name='transmutation'),
  MagicSchool(name='conjuration'),
  MagicSchool(name='necromancy'),
  MagicSchool(name='evocation'),
  MagicSchool(name='abjuration'),
  MagicSchool(name='enchantment'),
  MagicSchool(name='divination'),

  # attributes
  Attribute(name='Strength'),
  Attribute(name='Dexterity'),
  Attribute(name='Constitution'),
  Attribute(name='Wisdom'),
  Attribute(name='Intelligence'),
  Attribute(name='Charisma'),

  # documents slugs
  DocumentSlug(slug='wotc-srd'),
  DocumentSlug(slug='dmag'),
  DocumentSlug(slug='o5e'),

  # document titles
  DocumentTitle(title='Deep Magic for 5th Edition'),
  DocumentTitle(title='Systems Reference Document'),
  DocumentTitle(title='Open5e OGL'),

  # document license urls
  DocumentLicenseURL(url='http://open5e.com/legal')

])

# guest
guest = User.create_user('guest@guest.com', 'guest', 'test123')


db.session.commit()

armor_comment = ArmorComment.add_comment('armor', guest.id, "this is my armor comment content")

weapon_comment = WeaponComment.add_comment('weapon', guest.id, "this is my weapon comment content")

spell_comment = SpellComment.add_comment('spell', guest.id, "this is my spell comment content")

class_comment = ClassComment.add_comment('class', guest.id, "this is my class comment content")

new_armor = Armor.create_armor(slug="slug", 
                                name="Slug", 
                                category_id=3, 
                                document__slug__id=1, 
                                document__title__id=1, 
                                document__license_url=1, 
                                ac_base=5, 
                                modifier_attributes=["Dexterity", "Wisdom"],
                                max_modifier=2, 
                                strength_required=12, 
                                cost_in_gp=0, 
                                # weight=10, 
                                stealth_disadvantage=False, 
                                author_user_id=guest.id)

comfy_sweater = Armor.create_armor(
  slug="comfy-sweater", 
  name="Comfortable Sweater", 
  category_id=2, 
  document__slug__id=None, 
  document__title__id=None, 
  document__license_url=None, 
  ac_base=10, 
  modifier_attributes=["Wisdom", "Charisma"],
  max_modifier=8, 
  strength_required=None, 
  cost_in_gp=10.5, 
  weight=1, 
  stealth_disadvantage=False, 
  author_user_id=guest.id
)

new_armor_comment = ArmorComment.add_comment('slug', guest.id, "this is my new  armor joining comment content")

hacksaw = Weapon.create_weapon(slug='hacksaw', name='Hacksaw', weapon_category=3, document__slug__id=None, document__title__id=None, document__license_url=None, cost_in_gp=10.5, weight=None, bonus=1, author_user_id=1, weapon_damage_rolls=[{'dice_no': 2, 'die_sides': 12, 'damage_type': 2, 'flat_damage': None, 'weapon_slug': 'hacksaw'}], weapon_property_assignments=[6,7])

make_explode = Spell.create_spell(slug='make-explode', name="Make Explode", description="You point your finger at an enemy. They explode.", higher_level="You make your target explode even harder. For each level above 3rd, 1d8 of piercing damage is dealt in a 10-foot radius via shrapnel", page=None, spell_range="100 ft", material="A rocket gun", ritual=False, duration="instant", concentration=False, casting_time="1 action", level=3, magic_school=3, document__slug__id=None, document__title__id=None, document__license_url=None, circles="Explosions", author_user_id=1, spell_components=["V", "S", "M"], class_slug_spell_assignments=[], archetype_spell_assignments=["Warlock: Path of the Exploder", "Druid: Druid that's interesting"])

player = PlayerClass.create_player_class(
  slug= 'doomsayer',
  name= 'Doomsayer',
  description= 'A man approaches. He speaks the word "doom". From everywhere, destruction ensues.',
  hit_die= 8,
  base_hp_at_1st_level= 10,
  tool_proficiency= 'Sextant, compass, game boy color',
  skill_proficiency= "Athletics, Regurgitation",
  starting_equipment= "A guitar, a bass, a rocket launcher",
  table= "Oh oh, no more table.",
  spellcasting_ability= 4,
  subtypes_name= "Night Child",
  document__slug__id= None,
  document__title__id= None,
  document__license_url= None,
  author_user_id= 1,
  armor_proficiencies = [1, 2, 5],
  prof_weapons = "Quarterstaffs, light crossbows",
  saving_throw_ids = [4, 5],
  homebrew_spell_slugs = ['make-explode'],
  api_spell_slugs = ["doom-of-serpent-coils", "doom-of-blue-crystal"]
)

db.session.add_all([new_armor_comment])

new_modifier = ArmorModifierAttribute.create_armor_modifier_attribute(armor_slug="slug", attribute="Strength")

db.session.commit()

